---
title: "Extra Galactic Background Light"
author: "Aaron Robotham"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Extra Galactic Background Light}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Load the libraries we need:

```{r}
library(ProSpect)
library(celestial)
library(foreach)
```

Encode the Madua and Dickenson 2014 CSFH function:

```{r}
MD14func = function(z, norm=0.00945){ #norm here is MD14 0.015*0.63 (latter Salp to Chab Driver correction)
  norm * ((1+z)^2.7) / ((1+((1+z)/2.9)^5.6))
}
```

Create a function to generate the Extra Galactic Background light:

```{r}
EBL = function(massfunc_z = MD14func, norm=0.00945, Zfinal=0.02, zvec = 10^seq(-3,1, by=0.1),
               SFRvec=rep(0.01,length(zvec)),
               filters=c('u_SDSS', 'g_SDSS', 'r_SDSS', 'i_SDSS', 'Z_VISTA', 'Y_VISTA',
                         'J_VISTA', 'H_VISTA', 'K_VISTA'), ...){
  
  data(Dale_NormTot)
  data(BC03lr)

  agevec = cosdistTravelTime(zvec, ref='planck') * 1e9 # Create age vector
  
  if(!is.null(massfunc_z)){ # You can either pass in an SFR function, or an SFRvec of the values at redshifts given by zvec
    SFRvec = massfunc_z(zvec, norm=norm)
  }
  
  covolvec = cosdistCoVol(zvec, OmegaM = 0.3, OmegaL=0.7, H0=70) * 1e9 #  x1e9 to get to Mpc^3 (output is Gpc^3)
  volweights = (c(0,diff(covolvec)) + c(diff(covolvec),0))/2 # This evens out the volume weights around bin edges
  filtout = foreach(i = filters)%do%{approxfun(getfilt(i))} # Generate our filter sets for quick generation
  
  tempSFH = approxfun(agevec, SFRvec, yleft = 0, yright = 0) # Generate our temporary SFH function to create our ZH
  Zvec = Zfunc_massmap_box(agevec, massfunc=tempSFH, Zfinal=Zfinal) # Create out closed box ZH
  
  fluxz = foreach(i = 1:length(agevec), .combine='rbind')%do%{
    tempSFH = approxfun(agevec - agevec[i], SFRvec, yleft = 0, yright = 0) # Create a SFH from the current time to the end of the Universe
    tempZH = function(x,...){approxfun(agevec - agevec[i], Zvec, yleft = 0, yright = 0)(x)} # Create a ZH from the current time to the end of the Universe
    
    ProSpectSED(SFH = SFHfunc, massfunc=tempSFH, z = zvec[i], agemax = max(agevec) - agevec[i], filtout=filtout, #Run ProSpect SED for our target tempSFH and tempZH
                Dale=Dale_NormTot, speclib=BC03lr, OmegaM = 0.3, OmegaL=0.7, H0=70, Z=tempZH, ...)$Photom*1e-26 # x1e-26To get to W/m2/Hz (output is Jansky)
  }
  
  fluxz = fluxz * volweights #weight by volume elements
  flux = colSums(fluxz) # sum epochs
  tempcen = cenwave[cenwave$filter %in% filters,'cenwave']
  tempfreq =  299792458/(tempcen/1e10)
  flux = flux * tempfreq * 1e9 # scale to nW/m2
  flux = flux / (4*pi) # scale to nW/m2/sr
  
  return(data.frame(wave=tempcen, flux=flux))
}
```

The wavelength is in Angstroms and the flux is nW/m2/sr (as per Driver et al 2016).

Now we can generate some EBL models:

```{r}
print(EBL())
print(EBL(norm=0.008))
print(EBL(norm=0.008, Zfinal=0.01))
```
