# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.colSums_wt_cpp <- function(mat, vec_wt = 1L) {
    .Call(`_ProSpect_colSums_wt_cpp`, mat, vec_wt)
}

.mat_vec_mult_col_cpp <- function(mat, vec = 1L, col_lim = 0L) {
    .Call(`_ProSpect_mat_vec_mult_col`, mat, vec, col_lim)
}

.mat_vec_mult_row_cpp <- function(mat, vec = 1L, row_lim = 0L) {
    invisible(.Call(`_ProSpect_mat_vec_mult_row`, mat, vec, row_lim))
}

.vec_add_cpp <- function(vec_base, vec_add = 0L) {
    invisible(.Call(`_ProSpect_vec_add_cpp`, vec_base, vec_add))
}

.vec_mult_cpp <- function(vec_base, vec_mult = 1L) {
    invisible(.Call(`_ProSpect_vec_mult_cpp`, vec_base, vec_mult))
}

.wave_rebin_cpp <- function(wave, wave_bin, wave_bin_lo, wave_bin_hi, logbin = FALSE) {
    invisible(.Call(`_ProSpect_wave_rebin_cpp`, wave, wave_bin, wave_bin_lo, wave_bin_hi, logbin))
}

.spec_rebin_cpp <- function(wave_in, flux_in, wave_out, invar_in = NULL, logbin_in = FALSE, logbin_out = FALSE) {
    .Call(`_ProSpect_spec_rebin_cpp`, wave_in, flux_in, wave_out, invar_in, logbin_in, logbin_out)
}

